name: connector
description: A two-way Dart RPC library that supports native Dart streams.
version: 0.0.2
author: Max Davidson <davidsonmax@gmail.com>
dependencies:
  quiver: ">=0.19.0 <0.20.0"
  uuid: ">=0.4.0 <0.5.0"
  bson: ">=0.1.23 <0.2.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
